// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDoLZxmj5cQf-ogKZagvcOz6iwFluws7Y',
    appId: '1:633462236485:web:de827f88fbb33fa71eca2c',
    messagingSenderId: '633462236485',
    projectId: 'vetinspect-9f9e6',
    authDomain: 'vetinspect-9f9e6.firebaseapp.com',
    databaseURL: 'https://vetinspect-9f9e6-default-rtdb.firebaseio.com',
    storageBucket: 'vetinspect-9f9e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENe0zjHdnz3Rs63w8x92_odswNhCZvAk',
    appId: '1:633462236485:android:379b8391bb68654b1eca2c',
    messagingSenderId: '633462236485',
    projectId: 'vetinspect-9f9e6',
    databaseURL: 'https://vetinspect-9f9e6-default-rtdb.firebaseio.com',
    storageBucket: 'vetinspect-9f9e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyrhYRM7AG2RxSYb-obYfbfbKNu2NSu4',
    appId: '1:633462236485:ios:e23d6b6a3462b2a01eca2c',
    messagingSenderId: '633462236485',
    projectId: 'vetinspect-9f9e6',
    databaseURL: 'https://vetinspect-9f9e6-default-rtdb.firebaseio.com',
    storageBucket: 'vetinspect-9f9e6.appspot.com',
    iosClientId: '633462236485-shs50llgf9414u1a8e7rlfs8in40r3r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.davaocityvet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyrhYRM7AG2RxSYb-obYfbfbKNu2NSu4',
    appId: '1:633462236485:ios:dcb717aee0ff35a61eca2c',
    messagingSenderId: '633462236485',
    projectId: 'vetinspect-9f9e6',
    databaseURL: 'https://vetinspect-9f9e6-default-rtdb.firebaseio.com',
    storageBucket: 'vetinspect-9f9e6.appspot.com',
    iosClientId: '633462236485-r8qooq5fp6tf4h85oucvpgneoh4g2ket.apps.googleusercontent.com',
    iosBundleId: 'com.example.davaocityvet.RunnerTests',
  );
}
