// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvb7t-P3827KVLJeErap8assKjSvEn0IQ',
    appId: '1:546131705992:web:80804bcb35494d547d9f3d',
    messagingSenderId: '546131705992',
    projectId: 'cityvet-eac85',
    authDomain: 'cityvet-eac85.firebaseapp.com',
    storageBucket: 'cityvet-eac85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC444D88s2ZhFYVuBYYfOiBqtKSx2wlgFk',
    appId: '1:546131705992:android:f6027454231a2cfb7d9f3d',
    messagingSenderId: '546131705992',
    projectId: 'cityvet-eac85',
    storageBucket: 'cityvet-eac85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8TCeNvL2N47x38dp2FBrTi7h03lsBiDA',
    appId: '1:546131705992:ios:a81bda4abe325d017d9f3d',
    messagingSenderId: '546131705992',
    projectId: 'cityvet-eac85',
    storageBucket: 'cityvet-eac85.appspot.com',
    iosClientId: '546131705992-v1rdbr0gpo9iv57tq53luaelinesl8ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.huhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8TCeNvL2N47x38dp2FBrTi7h03lsBiDA',
    appId: '1:546131705992:ios:a81bda4abe325d017d9f3d',
    messagingSenderId: '546131705992',
    projectId: 'cityvet-eac85',
    storageBucket: 'cityvet-eac85.appspot.com',
    iosClientId: '546131705992-v1rdbr0gpo9iv57tq53luaelinesl8ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.huhu',
  );
}
